### ISSUE TITLE
Old RBF files with time stamp don't get deleted

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores_mister#6]
It looks like many users are having problems because the updater grabs the new files but has kept some old jt*date.rbf files around. MiSTer tends to get those ones instead of the new ones.

@theypsilon, is it possible to make the updater remove all jt timestampped files from _Arcade/cores?

**Comment by theypsilon** [comment]
This is probably only affecting a subset of people who were using the older updater from pre-downloader times. Likely retro driven one. Will try to confirm this but in any case the fix is the same, removing that folder and running the updater again will just install the files that are currently distributed.

**Comment by theypsilon** [comment]
<img width="418" alt="image" src="https://user-images.githubusercontent.com/852246/222968676-8b266a60-6785-4a62-8fb7-4c9ec7a82578.png">

The updater and DB are fine. So this is the result of installing files manually or using old updaters that would not care about removing old files. Either way, the solution is to delete the cores folder and run the updater again.

I don't delete files that have not been installed with downloader/update_all by design. If I'd be removing files not installed by this tool, some people would complain too.

Furthermore, I have to put in doubt that this is affecting many users, as I don't see many reports after searching for them.

**Comment by jotego** [comment]
Thanks for checking it
